name: speedvector7drl
description: A fast-paced, turn-based racing game for 7DRL 2021

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  malison: any
  piecemeal: any

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
